<script setup lang="ts">
import type { StoryItem } from '../types/StoryItem'

const stories1: StoryItem[] = [
  {
    id: 1,
    title: 'TITEL 1',
    date: new Date(2025, 3, 15),
    description: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    id: 2,
    title: 'TITEL 2',
    date: new Date(2025, 2, 20),
    description: 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  },
  {
    id: 3,
    title: 'TITEL 3',
    date: new Date(2025, 5, 1),
    description: 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  }
]

const stories2: StoryItem[] = []

const stories3: StoryItem[] = [
  {
    id: 1,
    title: 'TITEL 1',
    date: new Date(2025, 2, 15),
    description: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    id: 2,
    title: 'TITEL 2',
    date: new Date(2025, 3, 20),
    description: 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  },
  {
    id: 3,
    title: 'TITEL 3',
    date: new Date(2025, 5, 1),
    description: 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  },
  {
    id: 4,
    title: 'TITEL 4',
    date: new Date(2025, 2, 15),
    description: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  },
  {
    id: 5,
    title: 'TITEL 5',
    date: new Date(2025, 3, 20),
    description: 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb',
  },
  {
    id: 6,
    title: 'TITEL 6',
    date: new Date(2025, 5, 1),
    description: 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  }
]
</script>

<template>
  <ProductionStoryListView :stories="stories1" />
  <ProductionStoryListView :stories="stories2" />
  <ProductionStoryListView :stories="stories3" />
</template>

<style scoped>

</style>