site_name: My Docs

extra:
  version:
    provider: mike
theme: readthedocs
nav:
  - Home: index.md
  - Build and Run:
      - Overview: build-run/index.md
      - Backend: build-run/backend.md
      - Frontend: build-run/frontend.md