site_name: My Docs

extra:
  version:
    provider: mike
theme: readthedocs

nav:
  - Home: index.md
  - Build & Run:
      - Backend: build-run/backend.md
      - Frontend: build-run/frontend.md
  - API Reference:
      - Overview & Auth: api/index.md
      - Events: api/events.md
      - Productions: api/productions.md
      - Blogs: api/blogs.md
      - Pricing: api/pricing.md
      - Resources (Tags/Locations): api/resources.md
  - Testing:
      - Overview: testing/index.md
      - Backend: testing/backend.md
      - Frontend: testing/frontend.md
