Table productions {
  id int [pk, increment]
  titel text
  ondertitel text
  description1 text
  description2 text
  genre text
  planning_id int
}

Table events {
  id int [pk, increment]
  starttime date [not null]
  endtime date [not null]
  price numeric(5,2)
  hall text
  production_id int [not null]
}

Table blogs {
  id int [pk, increment]
  titel text [not null]
  description text [not null]
}

Table production_blogs {
  production_id int [not null]
  blog_id int [not null]

  indexes {
    (production_id, blog_id) [pk]
  }
}

Table event_blogs {
  event_id int [not null]
  blog_id int [not null]

  indexes {
    (event_id, blog_id) [pk]
  }
}

Table tags {
  id int [pk, increment]
  tag text [not null]
}

Table production_tags {
  production_id int [not null]
  tag_id int [not null]

  indexes {
    (production_id, tag_id) [pk]
  }
}

Ref: events.production_id > productions.id [delete: cascade]

Ref: production_blogs.production_id > productions.id [delete: cascade]
Ref: production_blogs.blog_id > blogs.id [delete: cascade]

Ref: event_blogs.event_id > events.id [delete: cascade]
Ref: event_blogs.blog_id > blogs.id [delete: cascade]

Ref: production_tags.production_id > productions.id [delete: cascade]
Ref: production_tags.tag_id > tags.id [delete: cascade]