import { z } from "zod";
import {
  ApiKey,
  ApiKeySchema,
  Blog,
  BlogSchema,
  CreateAccount,
  CreateAccountSchema,
  CreateBlog,
  CreateBlogSchema,
  CreateEvent,
  CreateEventSchema,
  CreateProduction,
  CreateProductionSchema,
  CreateTag,
  CreateTagSchema,
  Event,
  EventSchema,
  Production,
  ProductionSchema,
  PublicAccount,
  PublicAccountSchema,
  Tag,
  TagSchema,
  UpdateAccount,
  UpdateAccountSchema,
  UpdateBlog,
  UpdateBlogSchema,
  UpdateEvent,
  UpdateEventSchema,
  UpdateProduction,
  UpdateProductionSchema,
  UpdateTag,
  UpdateTagSchema,
  VerifyApiKey,
  VerifyApiKeySchema,
} from "./database_objects";

// Een voorbeeld van een globaal schema...
export const HelloWorldSchema = z.object({
  text: z.string(),
});

// list of all exports: (this way only need to import this file.)
export {
  ProductionSchema,
  CreateProductionSchema,
  UpdateProductionSchema,
  EventSchema,
  CreateEventSchema,
  UpdateEventSchema,
  BlogSchema,
  UpdateBlogSchema,
  CreateBlogSchema,
  TagSchema,
  CreateTagSchema,
  UpdateTagSchema,
  CreateAccountSchema,
  PublicAccountSchema,
  UpdateAccountSchema,
  ApiKeySchema,
  VerifyApiKeySchema,
};
export type {
  Production,
  CreateProduction,
  UpdateProduction,
  Event,
  CreateEvent,
  UpdateEvent,
  Tag,
  CreateTag,
  UpdateTag,
  Blog,
  CreateBlog,
  UpdateBlog,
  UpdateAccount,
  PublicAccount,
  CreateAccount,
  ApiKey,
  VerifyApiKey,
};
export type HelloWorld = z.infer<typeof HelloWorldSchema>;
