name: Frontend Tests

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  frontend-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm i

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test --filter=frontend