name: Pull Request Build and Deploy

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # STAP 1: Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check DB Port
        run: |
          echo "Checking if PostgreSQL is listening on port 5432..."
          nc -zv 127.0.0.1 5432 || echo "Port 5432 is CLOSED"

      - name: Create env file
        run: |
          echo "DB_USER_DEV=selab2" >> backend/.env
          echo "DB_HOST_DEV=127.0.0.1" >> backend/.env
          echo "DB_NAME_DEV=viernulvier" >> backend/.env
          echo "DB_PASSWORD_DEV=${{ secrets.DB_PASSWORD_DEV }}" >> backend/.env
          echo "DB_PORT_DEV=5432" >> backend/.env

      # STEP 2: Build & Test
      - name: Install and Test
        run: |
          npm i
          npm run test
        env:
          DB_USER_DEV: selab2
          DB_HOST_DEV: 127.0.0.1
          DB_NAME_DEV: viernulvier
          DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
          DB_PORT_DEV: 5432

      # STAP 3: Deploy (Lokaal op de server)
      - name: Deploy preview
        run: |
          PR_PATH="/home/selab2/project/previews/${{ github.event.pull_request.number }}"
          mkdir -p $PR_PATH
          # Gebruik rsync om de bestanden lokaal te kopiëren zonder rotzooi
          rsync -av --delete --exclude 'node_modules' --exclude '.git' . $PR_PATH/