name: Pull Request Build and Deploy

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # STAP 1: Node setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create env files
        run: |
          write_env() {
            echo "DB_USER_DEV=selab2" >> $1
            echo "DB_HOST_DEV=sel2-4.ugent.be" >> $1
            echo "DB_NAME_DEV=selab2_dev" >> $1
            echo "DB_PASSWORD_DEV=${{ secrets.DB_PASSWORD_DEV }}" >> $1
            echo "DB_PORT_DEV=2002" >> $1
          }
          write_env ".env"
          write_env "backend/.env"

      # STEP 2: Build & Test
      - name: Install and Test
        run: |
          npm i
          ls -la /var/run/postgresql/ || echo "No socket found"
          npm run test --filter=backend
        env:
          DB_USER_DEV: selab2
          DB_HOST_DEV: sel2-4.ugent.be
          DB_NAME_DEV: selab2_dev
          DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
          DB_PORT_DEV: 2002

      # STAP 3: Deploy (Lokaal op de server)
      - name: Deploy preview
        run: |
          PR_PATH="/home/selab2/project/previews/${{ github.event.pull_request.number }}"
          mkdir -p $PR_PATH
          # Gebruik rsync om de bestanden lokaal te kopiëren zonder rotzooi
          rsync -av --delete --exclude 'node_modules' --exclude '.git' . $PR_PATH/